// App-identity constants. Keep these in sync with `release.config` at the
// repo root (the shell-side source of truth) and the Swift mirror in
// `app/Sources/NepaliCalendar/AppConstants.swift`. Any change here should
// land in all three.
//
// Per-release values (version, build, sha256) are NOT here — those flow
// from `web/public/downloads/latest.json`, which is generated by
// `app/release.sh` and imported directly where needed.

/** Bundle/folder name — matches the .app folder and the DMG filename stem. */
export const BUNDLE_NAME = "NepaliCalendar";

/** Human-facing name. */
export const DISPLAY_NAME = "Nepali Calendar";

/** macOS bundle identifier. */
export const BUNDLE_ID = "app.nabinkhair.NepaliCalendar";

/** Public website hostname (no scheme). */
export const WEBSITE_HOST = "calendar.nabinkhair.com.np";

/** GitHub repo in owner/name form. */
export const GITHUB_REPO = "nabinkhair42/nepali-calendar";

// Derived URLs — assembled once here so callers don't reassemble.

export const DMG_FILENAME = `${BUNDLE_NAME}.dmg`;
export const DOWNLOAD_URL = `/downloads/${DMG_FILENAME}`;
export const MANIFEST_URL = "/downloads/latest.json";
export const GITHUB_RELEASES_URL = `https://github.com/${GITHUB_REPO}/releases`;
